### ISSUE TITLE
A question about KITTI raw dataset

### ISSUE THREAD

**Issue by kxhit** [xuanyuzhou98/SqueezeSegV2#4]
Thanks for sharing your work!
I have a problem about your lidar_2d data, which only has 10848 .npy files. But there are 12915 files raw data with tracklets in KITTI dataset.
Do you throw away some files? Could you verify this problem?
Thanks! Waiting for your reply.
The same issue is here: https://github.com/BichenWuUCB/SqueezeSeg/issues/35

**Comment by jrbin** [comment]
The interested objects are per. cyl. car. Only the 10848 images include these objects.

**Comment by kxhit** [comment]
I see, thank you! I think the images  that do not contain these objects can be treated as negative samples. Maybe it doesn't matter, because the negative samples are far more than the positive samples.
